### CREATE ROLE
POST http://localhost:3000/employee
Content-Type: application/json


{
"firstName": "Somchai",
"lastName": "Jaidee",
"position": "Programmer",
"salary": 48000,
"hireDate": "2024-06-01"
}


### READ ALL ROLES
GET http://localhost:3000/employee


### READ ROLE BY ID
GET http://localhost:3000/employee/1



### UPDATE ROLE
PUT http://localhost:3000/employee/1
Content-Type: application/json


{
"firstName": "Somchai",
"lastName": "Jaidee",
"position": "Senior Programmer",
"salary": 55000,
"hireDate": "2024-06-01"
}


### DELETE ROLE
DELETE http://localhost:3000/employee/1